name: Publish to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: benjlevesque/short-sha@v1.2
        name: Setting short SHA
        id: short-sha
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kodingg/dicc-client:latest,kodingg/dicc-client:${{ steps.short-sha.outputs.sha }}